import AsyncStorage from "@react-native-async-storage/async-storage";
import React, { createContext, useState, useContext, useEffect } from "react";

const LanguageContext = createContext();

export const translations = {
  tr: {
    typeMovies: "Film",
    typeTvSeries: "Dizi",
    favorites: "Favorilerim",
    watchList: "İzleme",
    watchedMovies: "İzlenen Filmler",
    watchedTv: "İzlenen Diziler",
    date: "Tarih",
    remaining: "Kalan Zaman",
    month: "Ay",
    days: "Gün",
    today: "Bugün",
    tvShows: "Diziler",
    movies: "Filmler",
    search: "Ara",
    settings: "Ayarlar",
    profile: "Profil",
    overview: "Özet",
    cast: "Oyuncular",
    showAll: "Tümünü Göster",
    collapse: "Daralt",
    videos: "Videolar",
    keywords: "Anahtar Kelimeler",
    similarMovies: "Benzer Filmler",
    recommendedMovies: "Önerilen Filmler",
    recommendedTvShows: "Önerilen Diziler",
    reviews: "Yorumlar",
    watchProviders: "İzleme Seçenekleri",
    year: "Yıl",
    duration: "Dakika",
    revenue: "Hasılat",
    noOverview: "Özet bulunmuyor.",
    noTagline: "Slogan bulunmuyor",
    votes: "oy",
    loading: "Yükleniyor...",
    searchMovies: "Film Ara",
    searchTvShows: "Dizi Ara",
    searchPlaceholderMovie: "Film Ara...",
    searchPlaceholderTv: "Dizi Ara...",
    noResults: "Sonuç bulunamadı",
    startTyping: "Aramak için yazın...",
    error: "Hata",
    crew: "Ekip",
    guestStars: "Konuk Oyuncular",
    season: "Sezon",
    episode: "Bölüm",
    airDate: "Yayın Tarihi",
    runtime: "Süre",
    rating: "Puan",
    mostVoted: "En Çok Oy Alanlar",
    popular: "Popüler",
    mostVotedTv: "En Çok Oylanan",
    popularityTv: "Popülerlik",
    general: "Genel",
    language: "Dil",
    darkMode: "Karanlık Mod",
    theme: "Tema",
    content: "İçerik",
    notifications: "Bildirimler",
    adultContent: "Yetişkin İçeriği",
    autoPlay: "Otomatik Oynatma",
    snow: "Kar animasyonu",
    clearCache: "Önbelleği temizle",

    clearCacheMessage:
      "Tüm önbellek temizlenecek. Devam etmek istiyor musunuz?",
    logoutMessage: "Çıkış yapmak istediğinizden emin misiniz?",
    cancel: "İptal",
    confirm: "Onayla",
    success: "Başarılı",
    cacheCleared: "Önbellek temizlendi",
    errorClearingCache: "Önbellek temizlenirken hata oluştu",
    about: "Hakkında",
    episodeCountUnknown: "Bölüm sayısı belirsiz",
    dateUnknown: "Tarih belirsiz",
    notYetRated: "Henüz oylanmamış",
    noOverviewAvailable: "Özet bulunmuyor.",
    noSeasonInfo: "Henüz sezon bilgisi bulunmuyor.",
    episodeRatings: "Bölüm Reytingleri",
    seasons: "Sezonlar",
    tvInformation: "Dizi Bilgisi",
    lightTheme: "Açık Tema",
    darkTheme: "Karanlık Tema",
    grayTheme: "Gri Tema",
    blueTheme: "Mavi Tema",
    orangeTheme: "Turuncu Tema",
    greenTheme: "Yeşil Tema",
    time: "dakika",
    noGenreInfo: "Tür bilgisi bulunmuyor.",
    country: "Ülke",
    type: "Tip",
    status: "Durum",
    productCompanies: "Yapım Şirketleri",
    network: "Yayıncı",
    answer:
      "Merhaba, size nasıl yardımcı olabilirim? film veya dizi önerisinde bulunabilirim",
    similarTvShows: "Benzer Diziler",
    logout: "Çıkış yap",
    data: "Veri",
    tvStatusEnd: "Bitti",
    tvStatusCon: "Devam Ediyor",
    email: "E-posta",
    password: "Şifre",
    passwordAgain: "Şifre Yeniden",
    forgotPassword: "Şifremi Unuttum",
    registerButton: "Kayıt ol",
    loginButton: "Giriş yap",
    name: "Adınız",
    lastName: "Soyadınız",
    forgotPasswordText:
      "E-posta adresinizi girin, size bir bağlantı gönderelim",
    registerToast: "  kayıt işleminiz başarılı bir şekile gerçekleşmiştir ",
    registerToast1: " e posta adresine doğrulama kodu gönderilmiştir",
    registerToast2:
      "Kayıt olma işlemi başarısız lütfen girdiğiniz bilgileri kontrol ediniz",
    loginToast: "Merhaba ",
    loginToast1:
      "Giriş hatası e posta veya şifrenizi kontrol edip yeniden deneyin",
    forgotPasswordToast:
      " e posta adresine şifre sıfırlama bağlantısı gönderildi",
    forgotPasswordToast1: "Geçersiz e posta adresi",
    detail: "Detaylar",
    PublicationDate: "Yayın tarihi",
    evaluation: "Kişi değerlendirdi",
    minutes: "Dakika",
    e: "B-",
    tryAgain: "Tekrar deneyin",
    mistake: "Bir hata oldu",

    tvShowsDetails: {
      favorites: "Favorilerim",
      watchList: "İzleme",
      watchedMovies: "izlenenler",
      watchedTv: "watchedTv",
      noTagline: "Slogan bulunmuyor",
      notYetRated: "Henüz oylanmamış",
      noOverviewAvailable: "Özet bulunmuyor.",
      videos: "Videolar",
      seasons: "Sezonlar",
      noSeasonInfo: "Sezon Bilgisi Bulunamadı",
      recommendedTvShows: "Önerlen Diziler",
      similarTvShows: "Benzer Diziler",
      reviews: "Yorumlar",
      loading: "Yükleniyor",
      noGenreInfo: "Tür Bilgisi Bulunamadı",
      tvInformation: "Dizi Bilgisi",
      votes: "Videolar",
      lists: "Listeler",
      episode: "Bölüm",
      airDate: "Yayın Tarihi",

      toastDell: "listesinden kaldırıldı!",
      toastAdd: "listesine ekleniyor!",
    },

    ChatModal: {
      placeholder: "Filmler veya diziler hakkında sorun veya öneri alın...",
      placeholderGenresMovies: "Bu türler ile ilgili filmler aranacak",
      placeholderGenresTv: "Bu türler ile ilgili diziler aranacak",
      movie: "Film",
      series: "Dizi",
      history: "Arama geçmişi",
      historyText: "Sohbet geçmişi yok",
    },
    SearchScreen: {
      search: "Ara",
      searchMovies: "Film Ara",
      searchTvShows: "Dizi Ara",
      searchActrist: "Oyuncu Ara",
    },
    ForgotPasswordScreen: {
      forgotPasswordToast:
        " e posta adresine şifre sıfırlama bağlantısı gönderildi",
      forgotPasswordToast1: "Geçersiz e posta adresi",
      forgotPasswordText:
        "E-posta adresinizi girin, size bir bağlantı gönderelim",
      forgotPassword: "Şifremi Unuttum",
      email: "E-posta",
      send: "Gönder",
      loginButton: "Giriş yap",
    },
    LoginScreen: {
      email: "E-posta",
      password: "Şifre",
      forgotPassword: "Şifremi Unuttum",
      registerButton: "Kayıt ol",
      loginButton: "Giriş yap",
      loginToast: "Merhaba ",
      loginToast1:
        "Giriş hatası e-posta veya şifrenizi kontrol edip yeniden deneyin",
    },
    RegisterScreen: {
      name: "Adınız",
      lastName: "Soyadınız",
      email: "E-posta",
      password: "Şifre",
      passwordAgain: "Şifre Tekrar",
      registerButton: "Kayıt ol",
      loginButton: "Giriş yap",
      registerToast: "Kayıt işleminiz başarılı bir şekile gerçekleşmiştir",
      registerToast1: " e posta adresine doğrulama kodu gönderilmiştir",
      registerToast2:
        "Kayıt olma işlemi başarısız lütfen girdiğiniz bilgileri kontrol ediniz",
    },
    movieScreens: {
      title: "Trend Filmler",
      voted: "En Çok Oylanan Filmler",
      popular: "En Polular Filmler",
      trendWeek: "Haftanın Trendleri",
      trendDay: "Günün Trendleri",
      oscar: "Oscar Ödüllü Filmler",
      theaters: "Vizyondaki Filmler",
      movieUpcaming: {
        upcaming: "Upcoming Movies",
        label: "Bu Hafta",
        label1: "Bu Ay",
        label2: "sonraki ay",
        label3: "sonraki 3 ay",
        label4: "Bu Yıl",
        label5: "Sonraki Yıl",
        label6: "Sonraki 3 Yıl",
      },
    },
    tvShowScreens: {
      title: "Trend Diziler",
      voted: "En Çok Oylanan Diziler",
      popular: "En Polular Diziler",
      trendWeek: "Haftanın Trendleri",
      trendDay: "Günün Trendleri",
      airingToday: "Bugün Yayınlanan Dizi Bölümleri",
      onTheAir:
        "Önümüzdeki 7 gün içerisinde yayınlanacak olan TV dizilerinin listesi",
    },
    profileScreen: {
      emailVerified: "E-postanız gönderilen link ile doğrulama yapınız",
      totalDuration: "Toplam Süre",
      movieStatistics: "Film İstatistikleri",
      tvShowStatistics: "Dizi İstatistikleri",
      minutes: " Dk",
      hours: " S",
      days: " Gün",
      weeks: "H",
      months: " Ay",
      years: " Yıl",
      movieWatched: "İzlenen Filmler",
      tvShowWatched: "İzlenen Diziler",
      tvShowCount: "Dizi Sayısı",
      tvShowEpisodetotalCount: "Bölüm Sayısı",
      tvShowSeasonCount: "Sezon Sayısı",
      selectAvatar: "Avatar Seç",
      close: "Kapat",
      logoutMessage: "Çıkış yapmak istediğinizden emin misiniz?",
      cancel: "İptal",
      confirm: "Onayla",
      ProfileLists: {
        lists: "Listeler",
        watchedMovies: "İzlenen Filmler",
        watchedTvSeries: "İzlenen Diziler",
        favorite: "Beğenilenler",
        watchList: "İzleme Listesi",
      },
      ProfileReminder: {
        reminder: "Hatırlatıcı",
        movieReminder: "Film Hatırlatıcıları",
        tvSeriesReminder: "Dizi Hatırlatıcıları",
        noTvSeriesReminder: "Dizi Hatırlatıcısı Bulunmuyor",
        noMovieReminder: "Film Hatırlatıcısı Bulunmuyor",
      },
      Notes: {
        notes: "Notlar",
        notesSave: "Kaydet",
        notesDelete: "Sil",
        notesEdit: "Düzenle",
        noNotesAddedYet: "Henüz not eklenmemiş",
      },
    },
  },

  en: {
    typeMovies: "Movie",
    typeTvSeries: "Tv Series",
    favorites: "Favorites",
    watchList: "Watch List",
    watchedMovies: "Watched Movies",
    watchedTv: "Watched Tv Series",
    date: "Date",
    remaining: "Remaining",
    month: "Month",
    days: "Day",
    today: "Today",
    tvShows: "TV Shows",
    movies: "Movies",
    search: "Search",
    settings: "Settings",
    profile: "Profile",
    overview: "Overview",
    cast: "Cast",
    showAll: "Show All",
    collapse: "Collapse",
    videos: "Videos",
    keywords: "Keywords",
    similarMovies: "Similar Movies",
    recommendedMovies: "Recommended Movies",
    recommendedTvShows: "Recommended TV Shows",

    reviews: "Reviews",
    watchProviders: "Watch Providers",
    year: "Year",
    duration: "Minutes",
    revenue: "Revenue",
    noOverview: "No overview available.",
    noTagline: "No tagline available",
    votes: "votes",
    loading: "Loading...",
    searchMovies: "Search Movies",
    searchTvShows: "Search TV Shows",
    searchPlaceholderMovie: "Search Movies...",
    searchPlaceholderTv: "Search TV Shows...",
    noResults: "No results found",
    startTyping: "Start typing to search...",
    error: "Error",
    crew: "Crew",
    guestStars: "Guest Stars",
    season: "Season",
    episode: "Episode",
    airDate: "Air Date",
    runtime: "Runtime",
    rating: "Rating",
    mostVoted: "Most Voted",
    popular: "Popular",
    mostVotedTv: "Most Voted",
    popularityTv: "Popularity",
    general: "General",
    language: "Language",
    darkMode: "Dark Mode",
    theme: "Theme",
    content: "Content",
    notifications: "Notifications",
    adultContent: "Adult Content",
    autoPlay: "Auto Play",
    snow: "Snow animation",
    clearCache: "Clear cache",
    clearCacheMessage: "All cache will be cleared. Do you want to continue?",
    logoutMessage: "Are you sure you want to log out?",
    cancel: "Cancel",
    confirm: "Confirm",
    success: "Success",
    cacheCleared: "Cache cleared",
    errorClearingCache: "Error clearing cache",
    about: "About",
    episodeCountUnknown: "Episode count unknown",
    dateUnknown: "Date unknown",
    notYetRated: "Not yet rated",
    noOverviewAvailable: "No overview available.",
    noSeasonInfo: "No season information available.",
    episodeRatings: "Episode Ratings",
    seasons: "Seasons",
    tvInformation: "Series Information",
    lightTheme: "Light Theme",
    darkTheme: "Dark Theme",
    grayTheme: "Gray Theme",
    blueTheme: "Blue Theme",
    orangeTheme: "Orange Theme",
    greenTheme: "Green Theme",
    time: "minutes",
    noGenreInfo: "No genre information available.",
    country: "Country",
    type: "Type",
    status: "Status",
    productCompanies: "Production Companies",
    network: "Network",
    answer: "Hello, how can I help you? I can suggest a movie or series",
    similarTvShows: "Similar series",
    logout: "Log out",
    data: "Data",
    tvStatusEnd: "Ended",
    tvStatusCon: "Continue",
    email: "E-mail",
    password: "Password",
    passwordAgain: "Password Again",
    forgotPassword: "Forgot password",
    registerButton: "Register",
    loginButton: "Log in",
    name: "Name",
    lastName: "Last Name",
    forgotPasswordText: "Enter your email address and we'll send you a link",
    registerToast: " Your registration has been completed successfully ",
    registerToast1: " A verification code has been sent to your email address",
    registerToast2:
      "Registration failed, please check the information you entered.",
    loginToast: "Hello ",
    loginToast1: "Login error. Check your email or password and try again.",
    forgotPasswordToast:
      " A password reset link has been sent to your email address.",
    forgotPasswordToast1: "Invalid email address",
    detail: "Detail",
    PublicationDate: "Publication date",
    evaluation: "People reviewed",
    minutes: "Minutes",
    e: "E-",
    tryAgain: "Try again",
    mistake: "There was a mistake",

    tvShowsDetails: {
      favorites: "Favorites",
      watchList: "Watch List",
      watchedMovies: "Watched Movie",
      watchedTv: "Watched TV",
      noTagline: "No Tagline",
      notYetRated: "Not Yet Ratec",
      noOverviewAvailable: "no Owerview Available.",
      videos: "Videos",
      seasons: "Seasons",
      noSeasonInfo: "No season info",
      recommendedTvShows: "Recommended TvShows",
      similarTvShows: "Similar TvShows",
      reviews: "Reviews",
      loading: "Loading",
      noGenreInfo: "No genre info",
      tvInformation: "Tv information",
      votes: "Videos",
      lists: "Lists",
      episode: "Episode",
      airDate: "Air Date",
      toastDell: "removed!",
      toastAdd: "added!",
    },

    ChatModal: {
      placeholder: "Ask for movies or series or get suggestions...",
      placeholderGenresMovies:
        "Movies related to these genres will be searched",
      placeholderGenresTv: "TV series related to these genres will be searched",
      movie: "Movie",
      series: "Series",
      history: "Search history",
      historyText: "No chat history",
    },
    SearchScreen: {
      search: "Search",
      searchMovies: "Search Movies",
      searchTvShows: "Search TV Shows",
      searchActrist: "Search Actor",
    },
    ForgotPasswordScreen: {
      forgotPasswordToast:
        " A password reset link has been sent to your email address.",
      forgotPasswordToast1: "Invalid email address",
      forgotPasswordText: "Enter your email address and we'll send you a link",
      forgotPassword: "Forgot Password",
      email: "Email",
      send: "Send",
      loginButton: "Log in",
    },
    LoginScreen: {
      email: "Email",
      password: "Password",
      forgotPassword: "Forgot Password",
      registerButton: "Register",
      loginButton: "Log in",
      loginToast: "Hello ",
      loginToast1: "Login error. Check your email or password and try again.",
    },
    RegisterScreen: {
      name: "Name",
      lastName: "Last Name",
      email: "Email",
      password: "Password",
      passwordAgain: "Password Again",
      registerButton: "Register",
      loginButton: "Log in",
      registerToast: "Your registration has been completed successfully",
      registerToast1:
        " A verification code has been sent to your email address",
      registerToast2:
        "Registration failed, please check the information you entered.",
    },
    movieScreens: {
      title: "Trend Movies",
      voted: "Most Voted Movies",
      popular: "Most Popular Movies",
      trendWeek: "Trends Of The Week",
      trendDay: "Trends Of The Day",
      oscar: "Oscar-Winning Movies",
      theaters: "Movies In Theaters",
      movieUpcaming: {
        upcaming: "Upcoming Movies",
        label: "This Week",
        label1: "This Month",
        label2: "Next Month",
        label3: "Next 3 Months",
        label4: "This Year",
        label5: "Next Year",
        label6: "Next 3 Years",
      },
    },
    tvShowScreens: {
      title: "Trend Series",
      voted: "Most Voted Series",
      popular: "Most Popular Series",
      trendWeek: "Trends Of The Week",
      trendDay: "Trends Of The Day",
      airingToday: "Episodes Airing Today",
      onTheAir: "List of TV series that will be broadcast in the next 7 days",
    },
    profileScreen: {
      emailVerified: "Your email has been verified with the link sent",
      totalDuration: "Total Duration",
      movieStatistics: "Movie Statistics",
      tvShowStatistics: "TV Show Statistics",

      minutes: " Minutes",
      hours: " Hours",
      days: " Days",
      weeks: " Weeks",
      months: " Months",
      years: " Years",
      movieWatched: "Movies Watched",
      tvShowWatched: "TV Shows Watched",
      tvShowCount: "Series Count",
      tvShowEpisodetotalCount: "Episode Count",
      tvShowSeasonCount: "Season Count",
      selectAvatar: "Select Avatar",
      close: "Close",
      logoutMessage: "Are you sure you want to log out?",
      cancel: "Cancel",
      confirm: "Confirm",
      ProfileLists: {
        lists: "Lists",
        watchedMovies: "Watched movies",
        watchedTvSeries: "Watched Tv Series",
        favorite: "Favorites",
        watchList: "Watch List",
      },
      ProfileReminder: {
        reminder: "Reminder",
        movieReminder: "Movie Reminder",
        tvSeriesReminder: "Tv Series Reminder",
        noTvSeriesReminder: "There is No Tv Series Reminder",
        noMovieReminder: "There is No Movie Reminder",
      },
      Notes: {
        notes: "Notes",
        notesSave: "Save",
        notesDelete: "Delete",
        notesEdit: "Edit",
        noNotesAddedYet: "No notes added yet",
      },
    },
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState("tr");
  useEffect(() => {
    const loadSettings = async () => {
      try {
        const savedLanguage = await AsyncStorage.getItem("selectedLanguage");
        if (savedLanguage !== null) {
          setLanguage(savedLanguage);
        }
      } catch (error) {
        console.error("Ayarlar yüklenemedi:", error);
      }
    };
    loadSettings();
  }, []);
  const toggleLanguage = async (language) => {
    setLanguage(language);
    try {
      await AsyncStorage.setItem("selectedLanguage", language);
    } catch (error) {
      console.error("Dil kaydedilemedi:", error);
    }
  };

  const value = {
    language,
    toggleLanguage,
    t: translations[language],
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
